[people]
    name = "jupiter123111"
[jupiter.logger.default]
    debug = true
    enableConsole = true
[jupiter.server.http]
    host = "0.0.0.0"
    port = 8200
[mysqlconfig]
    addr = "192.168.200.2:3306"
    user = "hell1"
    password = "worl1"
    junotpl = 1
[redisconfig]
    addr = "192.168.210.1:6379"
    junotpl = 3